# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/wp12974131.jpg'

# Special
background='#05041E'
foreground='#f3dbd2'
cursor='#f3dbd2'

# Colors
color0='#05041E'
color1='#696D8C'
color2='#907892'
color3='#6B8CA2'
color4='#A495A3'
color5='#D49BA5'
color6='#F4AEAC'
color7='#f3dbd2'
color8='#aa9993'
color9='#696D8C'
color10='#907892'
color11='#6B8CA2'
color12='#A495A3'
color13='#D49BA5'
color14='#F4AEAC'
color15='#f3dbd2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
